### ISSUE TITLE
Current nav highlight problems

### ISSUE THREAD

**Issue by anshumanv** [cerebro-iiitv/cerebro-web-2019#14]
Nav is not highlighted properly, I broke something lel gommenasai

![image](https://user-images.githubusercontent.com/21009455/52897337-4e319200-31f9-11e9-8485-b19b3282c85a.png)

**Comment by rossoskull** [comment]
No problem, will solve it once I reach hostel

**Comment by aashutoshrathi** [comment]
Thanks, @rossoskull 🎉
