### ISSUE TITLE
Make white cards dark, with black shadow

### ISSUE THREAD

**Issue by rossoskull** [cerebro-iiitv/cerebro-web-2019#34]
![screenshot from 2019-02-18 23-23-48](https://user-images.githubusercontent.com/27884543/52968843-83dea280-33d4-11e9-889b-86ded29c5be9.png)
![screenshot from 2019-02-18 23-25-03](https://user-images.githubusercontent.com/27884543/52968844-83dea280-33d4-11e9-870b-a0176f7e0160.png)

**Comment by anshumanv** [comment]
Please get rid of white entirely, use some dark-er shade instead.

**Comment by aashutoshrathi** [comment]
Yes, I can give you people samples:

![image](https://user-images.githubusercontent.com/21199234/52969616-fd779000-33d6-11e9-8f03-eebb90be4761.png)
