### ISSUE TITLE
Improve timeline component

### ISSUE THREAD

**Issue by rossoskull** [cerebro-iiitv/cerebro-web-2019#43]
Current timeline component doesn't fit well with the UI, improve it or take a look at https://www.npmjs.com/package/react-vertical-timeline-component

**Comment by anshumanv** [comment]
This was used last year and I genuinely think was better but then had to stick to mocks so suggested the component we're using now, nonetheless better to have it changed. 🎉

**Comment by aashutoshrathi** [comment]
Exactly @anshumanv  I just told him to follow what you did last year, that was far far better.

**Comment by anshumanv** [comment]
Lead 🙏
