### ISSUE TITLE
Spelling errors in About page

### ISSUE THREAD

**Issue by singhpratyush** [cerebro-iiitv/cerebro-web-2019#60]
The page says

> ... is one of the newly formed **IIIT** by the Ministry ...
> ...
> ... activities like **Technical Workshops**, events, talks and ...

while it should be 

> ... is one of the newly formed **IIITs** by the Ministry ...
> ...
> ... activities like **technical workshops**, events, talks and ...

**Comment by rossoskull** [comment]
Fixed :sparkles:
