### ISSUE TITLE
Inconsistent spacing in navbar

### ISSUE THREAD

**Issue by singhpratyush** [cerebro-iiitv/cerebro-web-2019#62]
The sign in button in the navbar is unevenly spaced as compared to other elements - 

![screenshot from 2019-02-21 07-31-32](https://user-images.githubusercontent.com/10860278/53138205-821b0780-35ab-11e9-991c-a3341eb5df5e.png)

A better version could be - 

![screenshot from 2019-02-21 07-35-49](https://user-images.githubusercontent.com/10860278/53138223-95c66e00-35ab-11e9-8195-b1811bb3918e.png)

Would just mean adding 
```css
margin-left: 2.3rem;
```
to the corresponding element.

And just as a personal opinion, maybe we can make the background for sign in button transparent (as in the above screenshot).

**Comment by rossoskull** [comment]
Fixed
