### ISSUE TITLE
Suggestion: Tooltip on actions

### ISSUE THREAD

**Issue by singhpratyush** [cerebro-iiitv/cerebro-web-2019#64]
We can have a tooltip saying "Unregister" when hovering on different possible action(s) in the "My Events" page.

![screenshot from 2019-02-21 07-41-47](https://user-images.githubusercontent.com/10860278/53138479-69f7b800-35ac-11e9-88c6-2542eb7e5f48.png)

-----

P.S.: @aashutoshrathi, your image is missing in the "Team" section.

**Comment by aashutoshrathi** [comment]
@singhpratyush Thanks for the update, will update the image. Someone tried to mess up with DB
