### ISSUE TITLE
Suggested changes on Homepage.

### ISSUE THREAD

**Issue by samagragupta** [cerebro-iiitv/cerebro-web-2019#9]
Suggested By Pranay Agarwal

![logo-final-png-03](https://user-images.githubusercontent.com/32234926/52393647-20e43600-2acd-11e9-9135-72fb25687edf.png)

- Size of logo should be smaller than current logo and should be replaced by this.

- Social divider should be below the bottom line of logo.

- Also consider about decreasing the margin of navbar.

- color should be #0A72BA  instead of #435eff

@aashutoshrathi @anshumanv @PiyushPawar17

**Comment by aashutoshrathi** [comment]
✨ Gawd is committing today 🎉
